DROP DATABASE gestion_fyl;
CREATE DATABASE IF NOT EXISTS gestion_fyl;
SHOW DATABASES;
USE gestion_fyl;

-- Edificios C
DROP TABLE IF EXISTS EDIFICIOS;
CREATE TABLE EDIFICIOS (
    ID_EDIFICIO VARCHAR(4),
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(100)
);

-- Pisos C
DROP TABLE IF EXISTS PISOS;
CREATE TABLE PISOS (
    ID_PISO SMALLINT,
    ID_EDIFICIO VARCHAR(4)
);

-- Apartamentos 
DROP TABLE IF EXISTS APARTAMENTOS;
CREATE TABLE APARTAMENTOS (
    ID_APARTAMENTO SMALLINT,
    ID_PISO SMALLINT,
    ID_EDIFICIO VARCHAR(4)
);

-- Tipos pagos
DROP TABLE IF EXISTS TIPOS_PAGOS;
CREATE TABLE TIPOS_PAGOS (
    ID_TIPO_PAGO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100)
);

-- Estados pagos
DROP TABLE IF EXISTS ESTADOS_PAGOS;
CREATE TABLE ESTADOS_PAGOS (
    ID_ESTADO_PAGO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100)
);

-- Pagos
DROP TABLE IF EXISTS PAGOS;
CREATE TABLE PAGOS (
    ID_PAGO BIGINT,
    FECHA_PAGO DATE,
    FECHA_LIMITE DATE,
    VALOR DECIMAL(10,2),
    DESCRIPCION VARCHAR(200),
    -- FK
    ID_ESTADO_PAGO SMALLINT,
    ID_TIPO_PAGO SMALLINT,
    ID_APARTAMENTO SMALLINT,
    ID_PISO SMALLINT,
    ID_EDIFICIO VARCHAR(4)
);

-- Usuarios y Roles
DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
    ID_ROL SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

-- Perfiles
DROP TABLE IF EXISTS PERFILES;
CREATE TABLE PERFILES (
    ID_PERFIL SMALLINT,
    ID_ROL SMALLINT,
    NOMBRE VARCHAR(50)
);

-- Tipos documentos
DROP TABLE IF EXISTS TIPOS_DOCUMENTOS;
CREATE TABLE TIPOS_DOCUMENTOS (
    ID_TIPO_DOCUMENTO SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50)
);

-- Usuarios
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    IDENTIFICACION VARCHAR(30),
    ID_TIPO_DOCUMENTO SMALLINT,
    CORREO VARCHAR(254),
    CELULAR VARCHAR(10),
    PRIMER_NOMBRE VARCHAR(50),
    SEGUNDO_NOMBRE VARCHAR (50),
    CONTRASENNA VARCHAR(100),
    PRIMER_APELLIDO VARCHAR(50),
    SEGUNDO_APELLIDO VARCHAR(50),
    ID_PERFIL SMALLINT
);
-- Propietarios
DROP TABLE IF EXISTS PROPIETARIOS;
CREATE TABLE PROPIETARIOS (
    IDENTIFICACION VARCHAR(30),
    ID_APARTAMENTO SMALLINT,
    ID_PISO SMALLINT,
    ID_EDIFICIO VARCHAR(4)
);

-- Tipos notificaciones
DROP TABLE IF EXISTS TIPOS_NOTIFICACIONES;
CREATE TABLE TIPOS_NOTIFICACIONES (
    ID_TIPO_NOTIFICACION SMALLINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200)
);

-- Notificaciones
DROP TABLE IF EXISTS NOTIFICACIONES;
CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(200),
    ID_PAGO BIGINT,
    ID_TIPO_NOTIFICACION SMALLINT
);

-- Formularios
DROP TABLE IF EXISTS FORMULARIOS;
CREATE TABLE FORMULARIOS (
    ID_FORMULARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_FORMULARIO VARCHAR(50),
    NODO_PRINCIPAL CHAR(1),
    DEPENDENCIA INT,
    ORDEN INT,
    ICONO VARCHAR(20),
    REDIRECT VARCHAR(20)
);
-- Permisos
DROP TABLE IF EXISTS PERMISOS;
CREATE TABLE PERMISOS (
    ID_PERFIL SMALLINT,
    ID_FORMULARIO INT,
    CREAR CHAR(1),
    EDITAR CHAR(1),
    LEER CHAR(1),
    ELIMINAR CHAR(1)
);

-- Auditoría y Errores
DROP TABLE IF EXISTS ERRORES;
CREATE TABLE ERRORES (
    CODIGO INT,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200)
);
-- Auditorias
DROP TABLE IF EXISTS AUDITORIAS;
CREATE TABLE AUDITORIAS (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TABLA VARCHAR(15),
    USUARIO VARCHAR(15),
    EVENTO VARCHAR(30),
    FECHA_CREACION DATE,
    INFORMACION VARCHAR(4000)
);



SET FOREIGN_KEY_CHECKS = 0;
-- EDIFICIOS
ALTER TABLE EDIFICIOS 
ADD CONSTRAINT PK_EDIFICIOS PRIMARY KEY(ID_EDIFICIO);
ALTER TABLE EDIFICIOS MODIFY NOMBRE VARCHAR(100) NOT NULL;
ALTER TABLE EDIFICIOS MODIFY DIRECCION VARCHAR(100) NOT NULL;
--

-- PISOS
ALTER TABLE PISOS 
ADD CONSTRAINT PK_PISOS PRIMARY KEY(ID_PISO, ID_EDIFICIO);
ALTER TABLE PISOS ADD CONSTRAINT fk_pisos_edificios FOREIGN KEY (ID_EDIFICIO) REFERENCES EDIFICIOS (ID_EDIFICIO);
--

-- APARTAMENTOS
ALTER TABLE APARTAMENTOS
ADD CONSTRAINT PK_APARTAMENTOS PRIMARY KEY (ID_APARTAMENTO, ID_PISO, ID_EDIFICIO);
ALTER TABLE APARTAMENTOS ADD CONSTRAINT fk_apartamentos_pisos FOREIGN KEY (ID_PISO, ID_EDIFICIO) REFERENCES PISOS (ID_PISO, ID_EDIFICIO);
--



-- ESTADOS_PAGOS
ALTER TABLE ESTADOS_PAGOS MODIFY NOMBRE VARCHAR(100) NOT NULL;
--

-- TIPOS_PAGOS
ALTER TABLE TIPOS_PAGOS MODIFY NOMBRE VARCHAR(100) NOT NULL;
--

-- PAGOS
ALTER TABLE PAGOS
ADD CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO);
ALTER TABLE PAGOS MODIFY FECHA_PAGO DATE NOT NULL;
ALTER TABLE PAGOS MODIFY FECHA_LIMITE DATE NOT NULL;
ALTER TABLE PAGOS MODIFY ID_ESTADO_PAGO SMALLINT NOT NULL;
ALTER TABLE PAGOS MODIFY VALOR DECIMAL(10,2) NOT NULL;
ALTER TABLE PAGOS MODIFY DESCRIPCION VARCHAR(200) NOT NULL;
ALTER TABLE PAGOS MODIFY ID_APARTAMENTO SMALLINT NOT NULL;
ALTER TABLE PAGOS MODIFY ID_PISO SMALLINT NOT NULL;
ALTER TABLE PAGOS MODIFY ID_EDIFICIO VARCHAR(4) NOT NULL;
ALTER TABLE PAGOS MODIFY ID_TIPO_PAGO SMALLINT NOT NULL;
ALTER TABLE PAGOS ADD CONSTRAINT fk_pagos_estados_pagos FOREIGN KEY (ID_ESTADO_PAGO) REFERENCES ESTADOS_PAGOS (ID_ESTADO_PAGO);
ALTER TABLE PAGOS ADD CONSTRAINT fk_pagos_tipos_pagos FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPOS_PAGOS (ID_TIPO_PAGO);
ALTER TABLE PAGOS ADD CONSTRAINT fk_pagos_apartamentos FOREIGN KEY (ID_APARTAMENTO, ID_PISO, ID_EDIFICIO) REFERENCES APARTAMENTOS (ID_APARTAMENTO, ID_PISO, ID_EDIFICIO);
--


-- ROLES
ALTER TABLE ROLES MODIFY NOMBRE VARCHAR(50) NOT NULL;
--

-- PERFILES
ALTER TABLE PERFILES
ADD CONSTRAINT PK_PERFILES PRIMARY KEY (ID_PERFIL);
ALTER TABLE PERFILES MODIFY NOMBRE VARCHAR(50) NOT NULL;
ALTER TABLE PERFILES MODIFY ID_ROL SMALLINT NOT NULL;
ALTER TABLE PERFILES ADD CONSTRAINT fk_perfiles_roles FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL);
--

-- TIPOS_DOCUMENTOS
ALTER TABLE TIPOS_DOCUMENTOS MODIFY NOMBRE VARCHAR(50) NOT NULL;
--

-- USUARIOS
ALTER TABLE USUARIOS
ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (IDENTIFICACION);
ALTER TABLE USUARIOS ADD CONSTRAINT uq_usuarios_correo UNIQUE (CORREO);
ALTER TABLE USUARIOS MODIFY CORREO VARCHAR(254) NOT NULL;
ALTER TABLE USUARIOS MODIFY PRIMER_NOMBRE VARCHAR(50) NOT NULL;
ALTER TABLE USUARIOS MODIFY CONTRASENNA VARCHAR(100) NOT NULL;
ALTER TABLE USUARIOS MODIFY PRIMER_APELLIDO VARCHAR(50) NOT NULL;
ALTER TABLE USUARIOS MODIFY ID_TIPO_DOCUMENTO SMALLINT NOT NULL;
ALTER TABLE USUARIOS MODIFY CELULAR varchar(10) NOT NULL;
ALTER TABLE USUARIOS MODIFY ID_PERFIL SMALLINT NOT NULL;
ALTER TABLE USUARIOS ADD CONSTRAINT fk_usuarios_perfiles FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL);
ALTER TABLE USUARIOS ADD CONSTRAINT fk_usuarios_tipos_documentos FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTOS (ID_TIPO_DOCUMENTO);
--

-- PROPIETARIOS
ALTER TABLE PROPIETARIOS
ADD CONSTRAINT PK_PROPIETARIOS PRIMARY KEY (IDENTIFICACION,ID_APARTAMENTO,ID_PISO, ID_EDIFICIO);
ALTER TABLE PROPIETARIOS ADD CONSTRAINT fk_propietarios_identificacion FOREIGN KEY (IDENTIFICACION) REFERENCES USUARIOS (IDENTIFICACION);
ALTER TABLE PROPIETARIOS ADD CONSTRAINT fk_propietarios_id_apartamento FOREIGN KEY (ID_APARTAMENTO, ID_PISO, ID_EDIFICIO) 
REFERENCES APARTAMENTOS (ID_APARTAMENTO, ID_PISO, ID_EDIFICIO);
--

-- TIPOS_NOTIFICACIONES
ALTER TABLE TIPOS_NOTIFICACIONES MODIFY NOMBRE VARCHAR(100) NOT NULL;
ALTER TABLE TIPOS_NOTIFICACIONES MODIFY DESCRIPCION VARCHAR(200) NOT NULL;
--

-- FORMULARIOS
ALTER TABLE FORMULARIOS MODIFY NOMBRE_FORMULARIO VARCHAR(50) NOT NULL;
ALTER TABLE FORMULARIOS MODIFY NODO_PRINCIPAL CHAR(1) NOT NULL;
ALTER TABLE FORMULARIOS MODIFY ORDEN INT NOT NULL;
ALTER TABLE FORMULARIOS MODIFY REDIRECT VARCHAR(20) NOT NULL;
ALTER TABLE FORMULARIOS ADD CONSTRAINT fk_formularios_dependencia FOREIGN KEY (DEPENDENCIA) REFERENCES FORMULARIOS (ID_FORMULARIO);
--

-- PERMISOS
ALTER TABLE PERMISOS
ADD CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERFIL, ID_FORMULARIO);
ALTER TABLE PERMISOS ADD CONSTRAINT fk_permisos_perfiles FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL);
ALTER TABLE PERMISOS ADD CONSTRAINT fk_permisos_formularios FOREIGN KEY (ID_FORMULARIO) REFERENCES FORMULARIOS (ID_FORMULARIO);
ALTER TABLE PERMISOS MODIFY CREAR CHAR(1) NOT NULL;
ALTER TABLE PERMISOS MODIFY EDITAR CHAR(1) NOT NULL;
ALTER TABLE PERMISOS MODIFY LEER CHAR(1) NOT NULL;
ALTER TABLE PERMISOS MODIFY ELIMINAR CHAR(1) NOT NULL;
--

-- NOTIFICACIONES
ALTER TABLE NOTIFICACIONES MODIFY DESCRIPCION VARCHAR(200) NOT NULL;
ALTER TABLE NOTIFICACIONES MODIFY ID_TIPO_NOTIFICACION SMALLINT NOT NULL;
ALTER TABLE NOTIFICACIONES MODIFY ID_PAGO BIGINT NOT NULL;
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT fk_notif_pagos FOREIGN KEY (ID_PAGO) REFERENCES PAGOS (ID_PAGO);
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT fk_notif_tipos FOREIGN KEY (ID_TIPO_NOTIFICACION) REFERENCES TIPOS_NOTIFICACIONES (ID_TIPO_NOTIFICACION);
--

-- ERRORES
ALTER TABLE ERRORES
ADD CONSTRAINT pk_CODIGO_errores PRIMARY KEY(CODIGO);     
ALTER TABLE ERRORES MODIFY NOMBRE VARCHAR(100) NOT NULL;
ALTER TABLE ERRORES MODIFY DESCRIPCION VARCHAR(200) NOT NULL;
--

-- AUDITORIA
ALTER TABLE AUDITORIAS MODIFY NOMBRE_TABLA VARCHAR(15) NOT NULL;
ALTER TABLE AUDITORIAS MODIFY USUARIO VARCHAR(15) NOT NULL;
ALTER TABLE AUDITORIAS MODIFY EVENTO VARCHAR(30) NOT NULL;
ALTER TABLE AUDITORIAS MODIFY FECHA_CREACION DATE NOT NULL;
ALTER TABLE AUDITORIAS MODIFY INFORMACION VARCHAR(4000) NOT NULL;
--
SET FOREIGN_KEY_CHECKS = 1;


--------------------------------------------------------------------------------------
--insertar datos en formularios

INSERT INTO FORMULARIOS
(
    ID_FORMULARIO,
    NOMBRE_FORMULARIO,
    NODO_PRINCIPAL,
    ORDEN,
    ICONO,
    REDIRECT
)
VALUES
(1,  'USUARIOS',              'Principal', 1,  '-', '/admin/usuarios');

INSERT INTO FORMULARIOS VALUES
(2,  'ROLES',                 'Principal', 2,  '-', '/admin/roles');

INSERT INTO FORMULARIOS VALUES
(3,  'PERFILES',              'Principal', 3,  '-', '/admin/perfiles');

INSERT INTO FORMULARIOS VALUES
(4,  'FORMULARIOS',           'Principal', 4,  '-', '/admin/formularios');

INSERT INTO FORMULARIOS VALUES
(5,  'PERMISOS',              'Principal', 5,  '-', '/admin/permisos');

INSERT INTO FORMULARIOS VALUES
(6,  'EDIFICIOS',             'Principal', 6,  '-', '/admin/edificios');

INSERT INTO FORMULARIOS VALUES
(7,  'PISOS',                 'Principal', 7,  '-', '/admin/pisos');

INSERT INTO FORMULARIOS VALUES
(8,  'APARTAMENTOS',          'Principal', 8,  '-', '/admin/apartamentos');

INSERT INTO FORMULARIOS VALUES
(9,  'PROPIETARIOS',          'Principal', 9,  '-', '/admin/propietarios');

INSERT INTO FORMULARIOS VALUES
(10, 'PAGOS',                 'Principal', 10, '-', '/admin/pagos');

INSERT INTO FORMULARIOS VALUES
(11, 'TIPOS_PAGOS',           'Principal', 11, '-', '/admin/tipos-pagos');

INSERT INTO FORMULARIOS VALUES
(12, 'ESTADOS_PAGOS',         'Principal', 12, '-', '/admin/estados-pagos');

INSERT INTO FORMULARIOS VALUES
(13, 'NOTIFICACIONES',        'Principal', 13, '-', '/admin/notificaciones');

INSERT INTO FORMULARIOS VALUES
(14, 'TIPOS_NOTIFICACIONES',  'Principal', 14, '-', '/admin/tipos-notificaciones');

COMMIT;

--insertar datos en roles
INSERT INTO ROLES VALUES
(1, 'Administrador'),
(2, 'Propietario');

---insertar datos en perfiles
INSERT INTO PERFILES VALUES
(1, 1, 'Administrador'),
(2, 2, 'D_A'),

--INSERTAR DATOS PERMISOS
INSERT INTO PERMISOS (
    ID_PERFIL,
    ID_FORMULARIO,
    CREAR,
    EDITAR,
    LEER,
    ELIMINAR
)
SELECT
    P.ID_PERFIL,
    F.ID_FORMULARIO,
    'N',
    'N',
    'S',
    'N'
FROM PERFILES P
JOIN FORMULARIOS F
ON F.NOMBRE_FORMULARIO = 'PAGOS'
WHERE P.NOMBRE_PERFIL = 'D_A';